### ISSUE TITLE
ships with two ship systems breaks MagicUI status bar

### ISSUE THREAD

**Issue by scardwell15** [MagicLibStarsector/MagicLib#17]
test with vanguard

not a hard break, but the status bar either draws under or over the second ship system

issue is in drawInterfaceStatusBar, does not take into account second ship system

**Comment by wispborne** [comment]
![image](https://user-images.githubusercontent.com/1343347/215873486-da624796-d29a-4132-922f-64535bdd7e77.png)

**Comment by scardwell15** [comment]
see pull #19
