### ISSUE TITLE
Windows defender tagging magiclib

### ISSUE THREAD

**Issue by fat4eyes-mwo** [MagicLibStarsector/MagicLib#65]
![image](https://github.com/MagicLibStarsector/MagicLib/assets/29511814/0cad11ec-ce45-4f53-8b41-d7cd67d2ffe7)
What's the advice on this?

**Comment by wispborne** [comment]
VirusTotal says it's clean.
https://www.virustotal.com/gui/file/7bde3d40a19b53aa4932697ed5e3114b0417938c1b2cdffa1ed6c63121d7e6b5
https://www.virustotal.com/gui/url/c58227c268135a9896c4d875a86234c7722534581b9dce710926eea2303f24a3?nocache=1
